@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

ManageUp *-right-> "1" UniquePersonList
ManageUp *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniquePersonList
UniqueTagList -[hidden]down- UniquePersonList

UniqueTagList -right-> "*" Tag
UniqueEmployeeList -right->C Employee

Employee -up-> "*" Tag

Employee *--> "1" Name
Employee *--> "1" Phone
Employee *--> "1" Email
Employee *--> "1" Position
Employee *--> "1" Department
Employee *--> "*" Task
@enduml
